import Head from 'next/head'

function addcoin() {
  return (
    <div>
      <Head>
        <title>CoinShooter | Add Coin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>Addcoin</h1>
    </div>
  );
}

export default addcoin;
