import Head from 'next/head'
import Promotedcoins from '../components/promotedcoins'
import Pagination from '../components/pagination'
import Table from '../components/table'
import AdvSection from '../components/AdvSection'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>CoinShooter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <AdvSection/>
      <Promotedcoins/>
      <div>
      <Table/>
      <Pagination/>
      </div>
      
      
    </div>
  )
}
