import Head from 'next/head'
import Header from "../components/header"
import Promotedcoins from '../components/promotedcoins'
import Table from '../components/table'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Promotedcoins/>
      
    </div>
  )
}
